import { AIProvider, ProviderCapability, ProviderHealth, ChatMessage, StructuredOutputOptions } from './provider';

export class MockProvider implements AIProvider {
  id = 'mock-provider';
  name = 'Mock AI Fallback';
  type = 'mock' as const;
  capabilities: ProviderCapability = {
    chat: true,
    vision: true,
    embeddings: true,
  };

  async healthCheck(): Promise<ProviderHealth> {
    return {
      status: 'CONNECTED',
      latency: 10,
    };
  }

  async getModels(): Promise<{id: string; name: string}[]> {
    return [];
  }

  async chat(messages: ChatMessage[]): Promise<string> {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 800));
    
    const lastUserMessage = [...messages].reverse().find(m => m.role === 'user')?.content || '';
    const isSystemPrompt = messages.some(m => m.role === 'system' && (m.content as string).toLowerCase().includes('agent'));
    const isAnalysis = messages.some(m => m.role === 'system' && (m.content as string).toLowerCase().includes('data analyst'));

    if (isAnalysis) {
      return `### Data Analysis Insights (Mock)\n\nBased on the provided statistics, the data appears to be within expected operational parameters. \n\n- The average values indicate steady performance.\n- No extreme anomalies were detected in the recent batch.\n\n*This is a simulated response generated by the Sovereign AI Mock Fallback because a live AI provider is unavailable.*`;
    }

    if (isSystemPrompt) {
      return `### Automated Agent Report (Mock)\n\nThe agent has successfully processed the request: "${lastUserMessage}". \n\n**Findings:**\n- Step 1 completed successfully.\n- Data verification passed.\n\n*This is a simulated agent report generated by the Sovereign AI Mock Fallback because a live AI provider is unavailable.*`;
    }

    return `I am currently operating in **Mock Fallback Mode** because a live AI provider (like Ollama or OpenAI) could not be reached. \n\nYou said: "${lastUserMessage}"\n\nTo get real responses, please start your local AI provider and update your configuration.`;
  }

  async *streamChat(messages: ChatMessage[]): AsyncGenerator<string, void, unknown> {
    const text = 'This is a streamed mock response from the MockProvider. It simulates real streaming!';
    const words = text.split(' ');
    
    for (const word of words) {
      await new Promise(r => setTimeout(r, 50)); // simulate network delay
      yield word + ' ';
    }
  }

  async generateStructuredOutput<T>(options: StructuredOutputOptions<T>): Promise<T> {
    await new Promise(resolve => setTimeout(resolve, 500));
    return {} as T;
  }

  async generateEmbedding(text: string): Promise<number[]> {
    return new Array(768).fill(0.1);
  }

  async analyzeImage(imageBase64: string, prompt: string): Promise<string> {
    await new Promise(resolve => setTimeout(resolve, 1000));
    return `### Vision Inspection Results (Mock)\n\nI have successfully scanned the provided image based on your prompt: "${prompt}".\n\n**Observations:**\n- The surface appears to be intact with no major structural defects.\n- Lighting is adequate for inspection.\n- No anomalies detected in this simulated scan.\n\n*Note: This is a simulated response from the Mock AI Fallback. Connect a real Vision Provider for accurate analysis.*`;
  }
}
